---

- name: Install
  include: install.yml
  tags:
    - build

- name: Configure
  include: configure.yml
  tags:
    - configure

- name: Basic check
  include: check.yml
  tags:
    - configure

- name: Enable monitoring
  include: monitor.yml
  tags:
    - configure
