services:
  - name: 'webapp'
    vagrant:
      ip: 192.168.10.0
      port: 8000
      sync: true
    docker:
      ip: 192.168.20.0
      port: 8000
      sync: true

  - name: 'database'
    vagrant:
      ip: 192.168.11.0
      port: 5432
      sync: false
    docker:
      ip: 192.168.21.0
      port: 8000
      sync: false
