---

- name: Configure local development environment using Vagrant
  hosts: localhost

  vars:
    base_dir: "{{ playbook_dir }}/../.."
    local_env_dir: "{{ base_dir }}/envs/local"

    services:
      - name: 'webapp'
        vagrant:
          ip: 192.168.10.0
          port: 8000
          sync: true
        docker:
          ip: 192.168.20.0
          port: 8000
          sync: true

      - name: 'database'
        vagrant:
          ip: 192.168.11.0
          port: 5432
          sync: false
        docker:
          ip: 192.168.21.0
          port: 8000
          sync: false

  tasks:
    - name: Create config dirs for each service
      file: path={{ local_env_dir }}/store/services/{{ item.name }} state=directory mode=0755
      with_items: "{{ services }}"

    - name: Create Vagrantfile for each service
      template:
        src: "Vagrantfile.j2"
        dest: "{{ local_env_dir }}/store/services/{{ item.name }}/Vagrantfile"
      vars:
        service: "{{ item }}"
      with_items: "{{ services }}"

    - name: Copy ansible.cfg for each service
      template:
        src: "ansible.cfg.j2"
        dest: "{{ local_env_dir }}/store/services/{{ item.name }}/ansible.cfg"
      with_items: "{{ services }}"
