---

dependencies:
  - role: ansible-users
    users:
      users:
        - name: '{{service.name}}'
          group: '{{service.name}}'
          shell: '/bin/bash'
          comment: 'deploy user'
          groups: 'wheel'
          pub_key: '{{service.name}}-id_rsa.pub'
          rc_files: ['.bashrc']

    tags:
      - build
