---

- name: Configure local development environment using Vagrant and Docker
  hosts: localhost

  vars:
    base_dir: '{{ playbook_dir }}/..'
    workspace_dir: '{{ base_dir }}/workspace'
    local_url: 'example.com'
    services:
      # - name: api
      #   ip: 192.168.10.13
      #   port: 80
      #   host_port: 8080
      #   sync_workspace: webapp  # tells which already existing folder in workspace should be synced
      #   type: vagrant  # what type of virtualization should be used - vagrant or docker

      - name: webapp
        repo: git@gitlab.com:mattkieblesz/mkitdevelopment.git
        ip: 192.168.10.10
        port: 80
        host_port: 8080
        type: vagrant

      - name: database
        ip: 192.168.10.11
        port: 5432
        type: vagrant

  roles:
    - dev_setup
