---

- name: Configure local development environment using Vagrant and Docker
  hosts: localhost

  vars:
    base_dir: '{{ playbook_dir }}/../..'
    workspace_dir: '{{ base_dir }}/workspace'
  vars_files:
    - 'vars.yml'

  roles:
    - dev_setup
